export const english = {
  pl: 'portfolio',
  homeAbout: {
    tit: 'Hi! 👋',
    desc: `I'm José Hidalgo Frontend developer focused on building beautiful interfaces and experiences`,
    butt: 'MORE ABOUT ME'
  },
  homePort: {
    desc: 'Some of my latest projects',
    butt: 'See all projects',
  },
  menu: {
    footer: 'Developed by José Hidalgo',
    text: 'Want to work with me?',
    menuList: {
      ho: 'Home',
      bl: 'Blog',
      ab: 'About me',
      po: 'Portfolio',
      co: 'Contact',
    },
    contDesc: {
      desc: 'If you want to communicate with me or are interested in starting a project together, get in touch.',
      em: 'Send me and email.',
      so: 'Or send me a direct message on my social media.',
    }
  },
  about: {
    h1: 'Hi! I am',
    h2: 'José Hidalgo',
    p1: 'Fronted Developer',
    abh1: 'About me',
    abp1: 'Hi! I am José Hidalgo. I have a great passion for design and technology. I specialize in Frontend development although I also have a background in Backend and my passion is building elegant and professional websites and user interfaces.',
    abp2: 'My first steps in development and programming were in college where I learned the basics of C ++, after that I discovered web development, which gave me and hooked me, so I decided to focus on it and forge a career in frontend developer. It was for this reason that I made the decision to learn everything related to web development in a self-taught way and thus be able to build professional and interactive websites.',
    abp3: 'Although my goal is to become a full Frontend developer, I will not be left alone with it. My goal is to take it to the next level and become a Full Stack developer. It was for this reason that I decided to join Henry where I learned technologies and work methodologies that would allow me to meet my goals.',
    abp4: 'I prepare myself daily to meet the challenges in this ever-changing world and will do my best to meet my goals.',
    skh1: 'My Skills',
    skp1: 'For development / coding, I use different tools specific to application or website development. The tools and technologies that I use and are familiar with are listed below.',
    skh41: 'Software / tools',
    skh42: 'Web development',
    mhh3: '“Choose a job you love and you will never have to work a day in your life.”',
    bt: 'See my work'
  },
  portfolio: {
    t1: 'My proyects',
    t2: 'About',
    ap1: 'My portfolio consists of designs for websites, applications, as well as some extra tools. In each job I put the maximum effort, perseverance, attention and creativity.',
    ap2: 'These are some of the projects that I develop. You can also find the code of each project on my github.',
    cards: [
      {
        title: 'React Gift Mobile Web App',
        img: 'https://repository-images.githubusercontent.com/317066963/23376800-4bf0-11eb-82c4-044ecde992f3',
        descTitle: 'Project descriptión.',
        desc: "Expensify is an application that let's you manage and keep track of your expense. It was built with React JS, Redux and Firebase for my database.",
        liTitle1: 'Platform',
        liDesc1: 'Web/Mobile',
        liTitle2: 'Category',
        liDesc2: 'Productivity',
        liTitle3: 'Developer',
        liDesc3: 'José Hidalgo',
        techT: 'Technologies Used',
        techP: "HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>SASS<span>/</span>React<span>/</span>Redux<span>/</span><br/>Firebase<span>/</span>Webpack",
        butDemo: 'Launch App',
        butRepo: 'Source Code',
        linkDemo: 'https://gif9.netlify.app/',
        linkRepo: 'https://github.com/ImJoseHidalgo/giffApp',
      },
      {
        title: 'React Gift Mobile Web App',
        img: 'https://repository-images.githubusercontent.com/317066963/23376800-4bf0-11eb-82c4-044ecde992f3',
        descTitle: 'Project descriptión.',
        desc: "Expensify is an application that let's you manage and keep track of your expense. It was built with React JS, Redux and Firebase for my database.",
        liTitle1: 'Platform',
        liDesc1: 'Web/Mobile',
        liTitle2: 'Category',
        liDesc2: 'Productivity',
        liTitle3: 'Developer',
        liDesc3: 'José Hidalgo',
        techT: 'Technologies Used',
        techP: "HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>SASS<span>/</span>React<span>/</span>Redux<span>/</span><br/>Firebase<span>/</span>Webpack",
        butDemo: 'Launch App',
        butRepo: 'Source Code',
        linkDemo: 'https://gif9.netlify.app/',
        linkRepo: 'https://github.com/ImJoseHidalgo/giffApp',
      },
      {
        title: 'React Gift Mobile Web App',
        img: 'https://repository-images.githubusercontent.com/317066963/23376800-4bf0-11eb-82c4-044ecde992f3',
        descTitle: 'Project descriptión.',
        desc: "Expensify is an application that let's you manage and keep track of your expense. It was built with React JS, Redux and Firebase for my database.",
        liTitle1: 'Platform',
        liDesc1: 'Web/Mobile',
        liTitle2: 'Category',
        liDesc2: 'Productivity',
        liTitle3: 'Developer',
        liDesc3: 'José Hidalgo',
        techT: 'Technologies Used',
        techP: "HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>SASS<span>/</span>React<span>/</span>Redux<span>/</span><br/>Firebase<span>/</span>Webpack",
        butDemo: 'Launch App',
        butRepo: 'Source Code',
        linkDemo: 'https://gif9.netlify.app/',
        linkRepo: 'https://github.com/ImJoseHidalgo/giffApp',
      },
    ],
  },
  contact: {
    title: 'Get in touch.',
    desc: "en",
    fname: 'Your name',
    femail: 'Your email',
    fsubject: 'Subject',
    ftext: "YOUR MESSAGE   *To make a line break press the 'Shift + Enter' keys on the keyboard",
    fbutton: 'Send Message',
  }
}
export const spanish = {
  pl: 'portafolio',
  homeAbout: {
    tit: 'Hola! 👋',
    desc: `Soy José Hidalgo, desarrollador frontend enfocado en construir bellas interfases y experiencias de usuario.`,
    butt: 'MÁS DE MI'
  },
  homePort: {
    desc: 'Algunos de mis últimos proyectos',
    butt: 'Ver todos',
  },
  menu: {
    footer: 'Desarrollado por José Hidalgo',
    text: '¿Quieres trabajar conmigo?',
    menuList: {
      ho: 'Inicio',
      bl: 'Blog',
      ab: 'Sobre mi',
      po: 'Portafolio',
      co: 'Contacto',
    },
    contDesc: {
      desc: 'Si deseas comunicarte conmigo o te interesa comenzar un proyecto juntos, pónte en contacto.',
      em: 'Envíame un correo.',
      so: 'O envíame un mensaje directo en mis redes sociales.',
    }
  },
  about: {
    h1: 'Hola! Yo soy',
    h2: 'José Hidalgo',
    p1: 'Fronted Developer',
    abh1: 'Sobre mi',
    abp1: '¡Hola! Soy José Hidalgo. Tengo una gran pasión por el diseño y la tecnología. Me especializo en desarrollo Frontend aunque támbien tengo conocimiento en Backend y mi pasión es construir sitios web e interfaces de usuario elegantes y profesionales.',
    abp2: 'Mis primeros pasos en el desarrollo y la programacón fueron en la universidad donde aprendi las baces en C++, luego de eso descubri el desarrollo web, que me dascinó y me enganchó, así que decidí enfocarme a ello y forjar una carrera en como desarrollador frontend. Fue por esto que tome la desición de aprender de forma autodidacta todo lo relacionado con desarrollo web y asi poder construir sitios web profesionales e interactivos.',
    abp3: 'Aunque mi objetivo es convertirme en un desarrollador Frontend completo, no me quedaré solo con ello. Mi objetivo es llevarlo al siguiente nivel y convertirme en un desarrollador Full Stack. Fue por ello que decidi ingresar a Henry donde aprendi tecnologias y metodologias de trabajo que me permitieran cumplir mis metas.',
    abp4: 'Me preparo a diario para afrontar los desafíos en este mundo en constante cambio y haré todo lo posible para cumplir mis metas.',
    skh1: 'Mis Skills',
    skp1: 'Para el desarrollo / codificación, utilizo diferentes herramientas específicas para el desarrollo de la aplicación o sitio web. A continuación se enumeran las herramientas y tecnologías que utilizo y con las que estoy familiarizado.',
    skh41: 'Software / herramientas',
    skh42: 'Desarrollo web',
    mhh3: '"Elije un trabajo que te guste y nunca tendrás que trabajar un día de tu vida".',
    bt: 'Ve mi trabajo'
  },
  portfolio: {
    t1: 'Mis proyectos',
    t2: 'About',
    ap1: 'Mi portafolio consta de diseños para sitios web, aplicaciones, así como algunos tools extra. En cada trabajo pongo el máximo esfuerzo, constancia, atención y creatividad.',
    ap2: 'Estos son algunos de los proyectos que desarrolle. También podras encontrar el codigo de cada proyecto en mi github.',
    cards: [
      {
        title: 'React Gift Mobile Web App',
        img: 'https://repository-images.githubusercontent.com/317066963/23376800-4bf0-11eb-82c4-044ecde992f3',
        descTitle: 'Descripción del proyecto.',
        desc: "Expensify es una aplicación que le permite administrar y realizar un seguimiento de sus gastos. Fue construido con React JS, Redux y Firebase para mi base de datos.",
        liTitle1: 'Plataforma',
        liDesc1: 'Web/Mobil',
        liTitle2: 'Categoria',
        liDesc2: 'Productividad',
        liTitle3: 'Desarrollador',
        liDesc3: 'José Hidalgo',
        techT: 'Tecnologías Utilizadas',
        techP: "HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>SASS<span>/</span>React<span>/</span>Redux<span>/</span><br/>Firebase<span>/</span>Webpack",
        butDemo: 'Ejecutar aplicación',
        butRepo: 'Código fuente',
        linkDemo: 'https://gif9.netlify.app/',
        linkRepo: 'https://github.com/ImJoseHidalgo/giffApp',
      },
      {
        title: 'React Gift Mobile Web App',
        img: 'https://repository-images.githubusercontent.com/317066963/23376800-4bf0-11eb-82c4-044ecde992f3',
        descTitle: 'Descripción del proyecto.',
        desc: "Expensify es una aplicación que le permite administrar y realizar un seguimiento de sus gastos. Fue construido con React JS, Redux y Firebase para mi base de datos.",
        liTitle1: 'Plataforma',
        liDesc1: 'Web/Mobil',
        liTitle2: 'Categoria',
        liDesc2: 'Productividad',
        liTitle3: 'Desarrollador',
        liDesc3: 'José Hidalgo',
        techT: 'Tecnologías Utilizadas',
        techP: "HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>SASS<span>/</span>React<span>/</span>Redux<span>/</span><br/>Firebase<span>/</span>Webpack",
        butDemo: 'Ejecutar aplicación',
        butRepo: 'Código fuente',
        linkDemo: 'https://gif9.netlify.app/',
        linkRepo: 'https://github.com/ImJoseHidalgo/giffApp',
      },
      {
        title: 'React Gift Mobile Web App',
        img: 'https://repository-images.githubusercontent.com/317066963/23376800-4bf0-11eb-82c4-044ecde992f3',
        descTitle: 'Descripción del proyecto.',
        desc: "Expensify es una aplicación que le permite administrar y realizar un seguimiento de sus gastos. Fue construido con React JS, Redux y Firebase para mi base de datos.",
        liTitle1: 'Plataforma',
        liDesc1: 'Web/Mobil',
        liTitle2: 'Categoria',
        liDesc2: 'Productividad',
        liTitle3: 'Desarrollador',
        liDesc3: 'José Hidalgo',
        techT: 'Tecnologías Utilizadas',
        techP: "HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>SASS<span>/</span>React<span>/</span>Redux<span>/</span><br/>Firebase<span>/</span>Webpack",
        butDemo: 'Ejecutar aplicación',
        butRepo: 'Código fuente',
        linkDemo: 'https://gif9.netlify.app/',
        linkRepo: 'https://github.com/ImJoseHidalgo/giffApp',
      },
    ],
  },
  contact: {
    title: 'Ponte en contacto.',
    desc: "es",
    fname: 'Tu nombre',
    femail: 'Tu email',
    fsubject: 'Sujeto',
    ftext: "TU MENSAJE   *Para hacer un salto de linea preciona las teclas 'Shift + Enter' en el teclado",
    fbutton: 'Enviar mensaje',
  }
}